language: node_js
node_js:
    - 0.8
    - 0.9

before_install:
    - npm install -g grunt-cli

install:
    - npm install

env:
    global:
        - JEKYLL_VERSION: 1.4.1
        - SAUCE_USERNAME: bootstrap

script:
    - grunt --verbose --force
