language: node_js
node_js:
  - 0.11

before_install:
  - npm install -g grunt-cli
  - npm install -g bower

install:
  - npm install
  - bower install

env:
  global:
    - JEKYLL_VERSION: 1.4.1
    - SAUCE_USERNAME: bootstrap

before_script:
  - grunt --verbose --force

after_script:
  - grunt dev
  - grunt release
